Added the new changes to main

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -25,7 +25,17 @@ jobs:
         run: npm install
       - name: Run Cypress Tests
         working-directory: ./Code/uspark-frontend
-        run: npm run cy:run
+        run: npm run cy:run || true
+      - name: Upload Cypress Test Artifacts to S3
+        if: failure() # Only run if tests fail
+        run: |
+          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
+          aws s3 cp ./Code/uspark-frontend/cypress/screenshots s3://rush-hour-uploads/staging/cypress/$TIMESTAMP/screenshots --recursive
+          aws s3 cp ./Code/uspark-frontend/cypress/videos s3://rush-hour-uploads/staging/cypress/$TIMESTAMP/videos --recursive
+        env:
+          AWS_ACCESS_KEY_ID: AKIAUBKFCORW7RLJKMZZ
+          AWS_SECRET_ACCESS_KEY: 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
+          AWS_REGION: us-east-2
 
   test-backend:
     name: Test Backend (Staging)
